version: "3.8"
services:
  server:
    build: ./server
    image: tm77/dhanvantari-server
    container_name: server_c
    ports:
      - '4000:4000'
  client:
    build: ./client
    image: tm77/dhanvantari-client
    container_name: client_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  db:
    build: ./db
    image: tm77/dhanvantari-database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dhanvantari
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
